# .github/workflows/daily_message.yml

name: Send Daily Message

on:
  schedule:
    # 设置定时执行的时间，使用 Cron 表达式
    # 例如，每天早上 8 点执行 (UTC 时间，需要换算成北京时间，例如北京时间早上8点是UTC时间0点)
    - cron: '30 22 * * *' # 每天 UTC 22:30 执行（对应北京时间6:30）
  workflow_dispatch: # 允许手动触发

jobs:
  build-and-send:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 指定较旧的稳定Python版本

    - name: Print Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests==2.31.0
        pip install lunardate==0.2.2
        pip install python-dotenv==1.0.0
        # 显示已安装的包以便调试
        pip list

    - name: Verify config file
      run: |
        if [ -f "config.py" ]; then
          echo "Config file exists"
        else
          echo "Config file does not exist, creating..."
          echo '# Default config' > config.py
          echo 'START_DATE = "2099-01-01"' >> config.py
          echo 'CITY = "示例城市"' >> config.py
          echo 'WEATHER_API_KEY = "示例密钥"' >> config.py
          echo 'APP_ID = "示例AppID"' >> config.py
          echo 'APP_SECRET = "示例AppSecret"' >> config.py
          echo 'TEMPLATE_ID = "示例模板ID"' >> config.py
          echo 'USER_ID = "示例用户ID"' >> config.py
          echo 'BIRTHDAY_SOLAR = "01-01"' >> config.py
          echo 'BIRTHDAY_LUNAR = "01-01"' >> config.py
        fi

    - name: Run script
      env:
        # 从 GitHub Secrets 中读取配置信息并设置为环境变量
        START_DATE: ${{ secrets.START_DATE }}
        CITY: ${{ secrets.CITY }}
        WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
        # USER_ID可以是单个用户ID或多个用户ID（以逗号分隔）
        USER_ID: ${{ secrets.USER_ID }}
        BIRTHDAY_SOLAR: ${{ secrets.BIRTHDAY_SOLAR }}
        BIRTHDAY_LUNAR: ${{ secrets.BIRTHDAY_LUNAR }}
      run: |
        # 检查环境变量是否设置
        echo "检查环境变量..."
        if [ -z "$START_DATE" ]; then
          echo "警告: START_DATE 未设置"
        else
          echo "START_DATE 已设置"
        fi
        
        # 运行脚本
        python main.py